# Generated by Django 6.0.7 on 2026-07-30 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('projects', '0004_task_created_at_task_description_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='project',
            field=models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.CASCADE,related_name='inventory_items',to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
