# Generated by Django 6.0.7 on 2026-07-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_created_at_and_more'),
        ('projects', '0004_task_created_at_task_description_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='projects.project'),
        ),
    ]
