# Generated by Django 6.0.7 on 2026-07-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
