# Generated by Django 6.0.7 on 2026-07-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_minimum_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='minimum_stock',
        ),
    ]
